version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: create cloud formation stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name mystack-${CIRCLE_WORKFLOW_ID:0:5}
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["SHA256:4LWQM4BTqiVFk+yYEyoe+hz3mb/CjPflu0gE1Ke9Ceo"]
      - run:
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook
          command: |  
            ansible-playbook -i inventory.txt main.yml

workflows:
  exworkflow:
    jobs:
      #- create-infrastructure
      - configure-infrastructure