version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyse:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run audit

workflows:
  App-workflow:
    jobs:
      - build
      - test:
          requires:
            build
      - analyse:
        requires:
          - test
